title: "Apex Printers"
description: "High-quality printing, fast turnaround."
url: "https://kazehito.github.io"
baseurl: "/apex-printers.github.io"

author:
  name: "Apex Printers"
  email: "apex.printers2017@gmail.com"
  avatar: /assets/img/logo.png

navbar-links:
  Services: "services"
  Portfolio: "portfolio"
  Blog: "blog"
  Contact: "contact"

footer-links-active:
  email: true
  facebook: true
  instagram: true
  phone: true

social-network-links:
  email: "apex.printers2017@gmail.com"
  facebook: "apexprinters"
  instagram: "apexprinters"

site-theme: "classic"
