title: "Apex Printers"
description: "High-quality printing, fast turnaround."
url: "https://apex-printers.github.io" # leave as-is unless you add a custom domain later
baseurl: ""                             # keep empty for apex-printers.github.io

author:
  name: "Apex Printers"
  email: "apex.printers2017@gmail.com"   # update or remove
  avatar: /assets/img/logo.png          # upload your logo later to match this path

navbar-links:
  Services: "services"
  Portfolio: "portfolio"
  Blog: "blog"
  Contact: "contact"

footer-links-active:
  email: true
  facebook: true
  instagram: true
  phone: true

social-network-links:
  email: "apex.printers2017@gmail.com"
  facebook: "apexprinters"              # your handle/page
  instagram: "apexprinters"             # your handle

# Optional: colors
site-theme: "classic"  # you can leave this or try others per the theme docs
